## IRIS FLOWER CLASSFICATION


In [2]:
#importing essential modules
from sklearn import datasets
import pandas as pd
import numpy as np

In [3]:
iris = datasets.load_iris()#load the iris data from the datasets module of scikit learn
print(type(iris))

<class 'sklearn.utils.Bunch'>


Bunch refers to Dictionary format i.e. iris is the dictionary

Key Value pairs, key has to be unique

In [4]:
print(iris.keys())
#applying keys method on the iris dictionary

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


"data" key holds all the input data

"target" key hold the dependent variable labels

"targe_names" key hold the names of dependent variable labels

"feature_names" key holds the names of input variables

"DESCR" holds the description of the data

In [5]:
type(iris.data)
#data represent input data (4 columns)

numpy.ndarray

In [6]:
iris.data
#extracting the data from the data key of the iris dictionary

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
iris.feature_names
#extract the feature names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
iris.target
#print the labels of TV: 3 unique labels: 0,1,2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.target_names
#extract the names of TV labels

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
iris.DESCR
#print description of data

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

Data key holds the input features in array format

target key holds the labels of dependent variable in array format

In [11]:
x = iris.data #input array assigned as x
y = iris.target #output variable assigned as y

Scaling is a suggested measure in two type of algos:

1. Distance metric eg. PCA, KNN
2. SLope/Derivative/ Gradient

In [12]:
#standariztion process: using standard scaler
#scikit learn prime package: machine learning: sklearn
from sklearn.preprocessing import StandardScaler

#instantiate the standard scaler: create an instance
scaler = StandardScaler(copy=True, with_mean=True, with_std=True)

#fittng the scaler on data
#scaler.fit(df)#algo will apply all the required maths; mean and stdev of each variable

#samples_scaled = scaler.transform(df)
#result of the scaler is always in array form

samples_scaled = scaler.fit_transform(x)
print(samples_scaled)
print()
print(x)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

Dimension Reduction: PCA

For all the distance metric algorithms, dimension reduction is also suggested

PCA will align data to the axis so that the algorithm can effectively decode the relationships between the data points

In [13]:
# Import PCA
from sklearn.decomposition import PCA

# Create PCA instance: model
model = PCA() #all pcs will be used

# Apply the fit_transform method of model to grains: pca_features
x = model.fit_transform(samples_scaled)

#principal components or PCA features
x.shape

(150, 4)

In [14]:
import numpy as np

print(np.round(model.explained_variance_ratio_ * 100, 1))

[73.  22.9  3.7  0.5]


In [15]:
# Import PCA
from sklearn.decomposition import PCA

# Create PCA instance: model
model = PCA(n_components=2) #all pcs will be used

# Apply the fit_transform method of model to grains: pca_features
x = model.fit_transform(samples_scaled)

#principal components or PCA features
x.shape

(150, 2)

In [16]:
#split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=123)
#x here represents input features post PCA

In [17]:
x_test.shape

(60, 2)

In [18]:
#implement classification using KNN
from sklearn.neighbors import KNeighborsClassifier

#Gridsearchcv to tune the value of k along with cross validation
from sklearn.model_selection import GridSearchCV

#declare the dictionary of the hyperparameter to be tuned
parameters = {"n_neighbors": range(1, 50), "weights": ['uniform', 'distance']}#1 to 49

gridsearch = GridSearchCV(KNeighborsClassifier(), parameters, cv=10)
#simple cross validation, not repeated

gridsearch.fit(x_train, y_train)
#, "weights": ['uniform', 'distance']

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 50),
                         'weights': ['uniform', 'distance']})

In [19]:
#print the best value of k
gridsearch.best_params_

{'n_neighbors': 8, 'weights': 'uniform'}

In [20]:
#using gridsearch model to make predictions on the test data
y_pred = gridsearch.predict(x_test)


In [21]:
gridsearch.score(x_test,y_test)

0.9

In [22]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 15  1]
 [ 0  5 17]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.75      0.94      0.83        16
           2       0.94      0.77      0.85        22

    accuracy                           0.90        60
   macro avg       0.90      0.90      0.89        60
weighted avg       0.91      0.90      0.90        60



# Testing the model

In [ ]:
X_new =[4.8, 3.0, 1.4, 0.3]
X_new = X_new.reshape(1,-1)
# Make predictions
prediction = gridsearch.predict(X_new)

print("Prediction of Species: {}".format(prediction))